title: Xoptfoil2 new
description: Documentation
theme: just-the-docs
# remote_theme: just-the-docs/just-the-docs
url: https://jxjo.github.io/Xoptfoil2

aux_links:
  Github Repository: https://jxjo.github.io/Xoptfoil2
