title: Xoptfoil2
description: Documentation
theme: just-the-docs
# remote_theme: just-the-docs/just-the-docs
url: https://jxjo.github.io/Xoptfoil2

aux_links:
  Xoptfoil2 on Github: https://jxjo.github.io/Xoptfoil2

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/images/Xoptfoil2.png"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/jxjo/Xoptfoil2" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: "docs" # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red  
  tip:
    title: Tip
    color: purple
    opacity: 0.1