title: Xoptfoil2
description: Documentation le
theme: just-the-docs
# remote_theme: just-the-docs/just-the-docs
url: https://jxjo.github.io/Xoptfoil2

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
